### ISSUE TITLE
Beta Architecture

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#19]
This is architecture that needs to be put in place before the CDK ACT framework and AST manipulations can come in full force:

- [x] Python import bundler (py_freeze import bundler): https://github.com/demergent-labs/kybra/issues/25
- [x] get modulegraph to be installed automatically
- [x] use venv instead of virtualenv
- [x] incorporate the use of pyenv to ensure python 3.10 is installed on any system
- [x] explain to the user how to setup VS Code to point to 3.10 installed with pyenv, just for the typechecking...we could also have them use that interpreter specifically to avoid any doubts on how the environment is set up
- [x] Testing framework...we might want to pull azle/examples into its own repo and use the tests across everything?: https://github.com/demergent-labs/kybra/issues/22
- [x] Get rid of build.sh and just use __main__.py
- [x] How to represent records, variants, arrays, and other non-primitives in Python typing, how to represent all types (make an issue for each showing how they should look): https://github.com/demergent-labs/kybra/issues/20
- [x] Research diagnostic thing for the bois
- [x] IC object (just hook it up, get that plumbing to work): https://github.com/demergent-labs/kybra/issues/21
  - [x] Finish adding primitive types to tests in Kybra
  - [x] Add all tests to Azle
  - [x] Get tests to pass for Kybra in GitHub
- [x] TryFromVmValue and TryIntoVmValue for non-primitives, including the derive macros: https://github.com/demergent-labs/kybra/issues/23
- [x] Create many basic examples with tests
- [x] Fix one-tuples in Azle and in Kybra
  - [x] It seems like Boa is treating single-element arrays as the single element, instead of as an array (open issue based on what Boa people say in discord)
  - [x] Fix 1-tuples once reviewing the cdk integration
- [x] Allow types to be defined in multiple Python files, we might want to use modulegraph just to grab all of the raw file paths for analysis
  - [x] Write them to a file and read them from a file instead of trying to pass them on the command line, Azle should do this as well
- [x] stable storage: https://github.com/demergent-labs/kybra/issues/24
  - [x] I need the system methods working first
- [x] Examples
  - [x] date https://github.com/demergent-labs/kybra/issues/125
  - [x] stable memory
  - [x] generators
  - [x] call_raw
- [x] async functions and cross canister calls: https://github.com/demergent-labs/kybra/issues/26
- [x] Try to get rid of ic-cdk-optimizer and ic-wasm, and use the ic-wasm library if possible (need to wait on dfx 0.12.0-beta.4): https://github.com/demergent-labs/kybra/issues/42
- [x] All pybaseexceptions should print the good errors, fix this immediately https://github.com/demergent-labs/kybra/issues/126

**Comment by lastmjs** [comment]
- [ ] complex_types (has some sort of Python runtime error thing with the modules I think)

**Comment by lastmjs** [comment]
- [ ] Make the ManagementCanister and Ledger canister types

**Comment by lastmjs** [comment]
- [ ] Finish notify and notify_with_payment128

**Comment by lastmjs** [comment]
- [ ] Double-check that anywhere user and CDK code intermingles, that we use _prefix names for variables

**Comment by lastmjs** [comment]
- [ ] Change all examples to use __init__.py as the entrypoint

**Comment by lastmjs** [comment]
- [ ] All variables in Kybra and Azle need to have a CDK prefix

**Comment by lastmjs** [comment]
- [ ] Make sure all system methods allow async code appropriately
