### ISSUE TITLE
0.5.0

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#384]
- [x] Documentation
  - [x] document that the basic dfx deploy flow is what works, if you want to do anything else you'll have to manually figure it out
  - [x] Explain that installer will now be your own canister
  - [x] document that we only have 8 bytes of randomness instead of 32 temporarily
  - [x] All new features
  - [x] Explain that the binary hash is now useless
  - [x] We need to explain in the docs that object unpacking shouldn't be used: https://github.com/RustPython/RustPython/issues/4932
    - [x] ethereum_json_rpc and outgoing_http_requests might have these problems
  - [x] Explain in stable structures section that memory id 255/254 is taken
  - [x] Memory ids 0, 1, 2, 233, 234 are all taken
  - [x] breaking change...memory ids 0, 1, 2
  - [x] document all contributor stuff
- [x] This means the sender and receiver type has diverged, and can cause data loss. this is happening in Kybra, I think it was fixed in Azle?
- [x]  I removed guard functions entirely from init and post_upgrade, is that okay?
- [x] document the new issues with hashing, this should probably be in the security section
- [x] Make an MRE for this: https://github.com/RustPython/RustPython/issues/4932
- [x] Make sure we are complying with the PSF license...are we a derivative work of Python? Not sure, we might just have to summarize the changes we've made
- [x] explain that init or post_upgrade may appear to work locally, but you should check the replica logs
- [x] Explain how if anything goes wrong during post_upgrade or pre_upgrade, it's all over basically
- [x] Wasmer is broken on Ma cM1...we need a different way to get Candid to work
- [x] Use the old Candid hacks to get the Candid out of the canister
- [x] Compiling the stdlib on the Mac M1 is taking a disturbingly long amount of time
- [x] password-protected dfx is probably going to be an issue with post_install
- [x] document that the canister:service metadata will be innacurrate on the first deploy but not the second
- [x] I think we should get rid of the candid:service metadata for the time being, I opened up the Candid UI and it was just blank until I deployed again. If I remove the metadata I think that will fix it
- [x] Fix naive candid parsing: https://github.com/demergent-labs/kybra/issues/433
- [ ] Tell people that to upgrade to Kybra 0.5.0 they should delete ~/.config/kybra if it exists
- [ ] Document all breaking changes
  - [ ] delete ~/.config/kybra
  - [ ] dfx.json: post_install, wasm path without .gz, and gzip
  - [ ] void now required
  - [ ] Vec now required/used?
  - [ ] removing candid metadata is a breaking change
- [x] Fix this issue: Opt["nat"] which results in The type nat is used, but never defined. Make sure all candid types are defined correctly
- [x] Document the --artificial-delay 0 thing
- [x] make sure to document service everywhere
- [x] Make an issue to go through Azle and test out all code examples, and especially to update the Candid main example
- [x] Make sure to fix Vec syntax everywhere in the Azle and Kybra books
- [ ] uppercase Opt
- [ ] Vec instead of list
- [ ] uppercase variants
- [x] sign_with_ecdsa in azle reference has an incorrect link to an example
- [x] Major problem...projects without a did file that use init/post_upgrade params will not deploy...MUST BE FIXED
  - [x] Open forum thread or issue about --argument candid inference
- [x] Explain that when adding init/post_upgrade params you may want to start clean, and you'll have to manually add  the params to the service param list in the candid file
- [x] Go through the reference, especially updating Candid
- [x] Make sure to update the GitHub repo README.md as well, and make sure that it displays on PyPI
- [x] Go through the discord and all issues and make sure all documentation issues are addressed
- [x] Test dictionary unpacking everywhere (ethereum_json_rpc and outgoing_http_requests might have these problem) and update documentation if you must change these
- [x] add guard function documentation
- [x] open guard function issue for azle
